language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
env:
  global:
    - TRAVIS=true
services:
  - postgresql
  - mysql
before_script:
  - mysql -e 'create database sworm;'
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
